#1. Build frontend 
FROM node:24-slim as builder 

WORKDIR /repo

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY apps/web ./apps/web
COPY packages/shared ./packages/shared

WORKDIR /repo/apps/web

RUN npm run build

#2. Build nginx image
FROM nginx:stable

COPY nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /repo/apps/web/dist /usr/share/nginx/html