FROM node:24-slim 

WORKDIR /repo

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install 

COPY apps/web ./apps/web
COPY packages/shared ./packages/shared

WORKDIR /repo/apps/web 

EXPOSE 5173

CMD ["npm", "run", "dev"]